### ISSUE TITLE
(User Story #1) Link the enabling/disabling of the toggle to an "ANONYMOUS_ENABLED" flag in the backend

### ISSUE THREAD

**Issue by FatimaY810** [CMU-17313Q/fall23-nodebb-bugbusters#4]
We will have to implement some sort of connection between the frontend and backend, where if a user toggles the "Reply Anonymously" button, there should be some sort of flag that becomes "true" in the backend. This should then allow us to change the functions accordingly. E.g. when true, displaying the name of the replier should not be allowed as well as changing the display picture.

Estimated Effort: 4-5 hours (this should include understanding the relations between the frontend and backend and how to link actions that take place in the front end to the back end)
Dependencies: this is dependent on the issue #3 as we need the functionality of the toggle to be enabled first
Milestones: We would like this to be done in sprint 1
Acceptance Criteria: We will write test cases that will check if the flag is being correctly set to true/false depending on whether a user has posted anonymously or not. The test cases should also check what name is displayed

**Comment by boushrabnd** [comment]
I fixed the hard-coded anonymous user by changing the logic of anonymizing to anonymize for other users and not the author. I also added a test to make sure an anonymous author can identify their own posts
