### ISSUE TITLE
(User Story #1) Change the picture of the replier to a generic one when the "Reply Anonymously" button is toggled

### ISSUE THREAD

**Issue by FatimaY810** [CMU-17313Q/fall23-nodebb-bugbusters#6]
Idea for this:
Use a predetermined generic profile picture when the replier toggles the "Reply Anonymously" button. This will be their display picture for that reply. 

Estimated time: 1-2 hours (including building and understanding the bridge between the frontend and the backend and researching what modules we can import for randomness)
Dependencies: dependent on the completion of issue #3 and #4 since we need the enabling of the flag to start the randomness. This will also run parallel with issue #5 
Milestone: Sprint 1
Acceptance Criteria: we should be able to use grunt and see whether the picture has been changed to our generic one when we follow the steps:
1. create a post on NodeBB
2. reply to a post but toggle the "Reply Anonymously" to be on
3. Send in a reply 
4. Check whether the picture has been changed to our generic one of the replier

**Comment by boushrabnd** [comment]
Sara implemented this feature by adding an anonymous avatar picture to nodebb.
